### ISSUE TITLE
Impossible to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by Def2010** [Skycoder42/QtService#19]
1. Cloning sources
2. qmake && make:
...
.../QtService/src/service/service.pro:45: Cannot find feature qdep
Project ERROR: Failed to load qdep feature! Run 'qdep prfgen --qmake /usr/lib/x86_64-linux-gnu/qt5/bin/qmake' to create it.
...
make: *** [sub-src-make_first] Error 2
3. qdep prfgen --qmake /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
Traceback (most recent call last):
  File "/usr/local/bin/qdep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/qdep/internal/cli.py", line 163, in main
    prfgen(path.abspath(sys.argv[0]), res.qmake, res.dir)
  File "/usr/local/lib/python3.5/dist-packages/qdep/qdep.py", line 12, in prfgen
    qmake_res = sub_run([qmake, "-query", "QT_HOST_DATA"], check=True, stdout=subprocess.PIPE, encoding="UTF-8")
  File "/usr/local/lib/python3.5/dist-packages/qdep/internal/common.py", line 59, in sub_run
    return subprocess.run(*args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by Def2010** [comment]
If I remove ', encoding' from python scripts
1. qdep prfgen --qmake /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
Generating PRF-File as:  b'/usr/lib/x86_64-linux-gnu/qt5\n'/mkspecs/features/qdep.prf

(no errors or other output, file qdep.prf does not exists)
2. qmake & make 
... Cannot find feature qdep
Project ERROR: Failed to load qdep feature! Run 'qdep prfgen --qmake /usr/lib/x86_64-linux-gnu/qt5/bin/qmake' to create it.
